#Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
# Main Monitor
workspace = 1, monitor:eDP-1, persistent:true, default:true
workspace = 2, monitor:eDP-1, persistent:true
workspace = 3, monitor:eDP-1, persistent:true
workspace = 4, monitor:eDP-1, persistent:true
workspace = 5, monitor:eDP-1, persistent:true
